services:
  web:
    build: .
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
    environment:
      DATABASE_URL: mysql://root@database_default:3306/db
    links:
      - database_default
    restart: always

  database_default:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "database-default:/var/lib/mysql"

volumes:
  database-default:
