version: "3"

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./public:/var/www/public
    environment:
      DATABASE_URL: postgres://postgres@database_default:5432/db
    links:
      - "database_default"

  database_default:
    image: postgres:13.5-alpine
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      SERVICE_MANAGER: "fsm-postgres"
    volumes:
      - database-default:/var/lib/postgresql/data

volumes:
  database-default:
